baseurl = "/"
languageCode = "en-us"
title = "Usnish Majumdar: Blog"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = "blog-usnish-org"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "about"
    url = "https://usnish.org/"
    weight = 2
[[menu.main]]
    name = "tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "subscribe"
    url = "/index.xml"

[params]
    description = "Thanks!"
    footer = "Built with [hugo](http://gohugo.io/) and [hugo-xmin](https://github.com/yihui/hugo-xmin)."
